CREATE TABLE IF NOT EXISTS public.hadiths (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  topic text NOT NULL,
  content_pt text NOT NULL,
  content_en text,
  source text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Habilitar RLS
ALTER TABLE public.hadiths ENABLE ROW LEVEL SECURITY;

-- Política para permitir leitura pública de Hadiths
CREATE POLICY "hadiths_read_all" ON public.hadiths
  FOR SELECT USING (true);


INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Patience', 'Verdadeiramente, a paciência é aquela demonstrada no primeiro momento da calamidade.', 'Verily, the patience is at the first stroke of a calamity.', 'Sahih Bukhari');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Repentance', 'Allah fica mais satisfeito com o arrependimento do Seu servo do que qualquer um de vós ficaria ao reencontrar o seu camelo perdido num deserto vasto.', 'Allah is more pleased with the repentance of His slave than any one of you is with finding his lost camel in a barren desert.', 'Sahih Muslim');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Overcoming', 'O homem forte não é aquele que vence na luta, mas sim aquele que consegue controlar a si mesmo no momento da raiva.', 'The strong man is not the one who can wrestle, but the strong man is the one who can control himself when he is angry.', 'Sahih Bukhari');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Repentance', 'Todos os filhos de Adão são pecadores, mas os melhores entre os pecadores são aqueles que se arrependem.', 'All the sons of Adam are sinners, but the best of sinners are those who repent.', 'Sunan at-Tirmidhi');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Patience', 'Quão admirável é a situação do crente; há bem para ele em tudo, e isto aplica-se apenas ao crente. Se a prosperidade o alcança, ele agradece a Allah e isso é bom para ele; e se a adversidade o atinge, ele suporta-a com paciência e isso é melhor para ele.', 'How wonderful is the case of a believer; there is good for him in everything and this applies only to a believer. If prosperity attends him, he expresses gratitude to Allah and that is good for him; and if adversity befalls him, he endures it patiently and that is better for him.', 'Sahih Muslim');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Forgiveness', 'Se não cometêsseis pecados, Allah faria-vos desaparecer e substituir-vos-ia por outro povo que pecasse e, em seguida, pedisse perdão a Allah, e Ele perdoaria-os.', 'If you were not to commit sins, Allah would have swept you out of existence and would have replaced you by another people who have committed sin, and then asked forgiveness from Allah, and He would have granted them pardon.', 'Sahih Muslim');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Patience', 'Nenhum cansaço, doença, preocupação, tristeza, dano ou angústia atinge um muçulmano, mesmo que seja o picar de um espinho, sem que Allah expie alguns dos seus pecados por causa disso.', 'No fatigue, nor disease, nor sorrow, nor sadness, nor hurt, nor distress befalls a Muslim, even if it were the prick he receives from a thorn, but that Allah expiates some of his sins for that.', 'Sahih Bukhari');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Overcoming', 'Certamente, Allah não olha para os vossos corpos nem para as vossas aparências, mas sim para os vossos corações.', 'Verily, Allah does not look towards your bodies nor towards your appearances, but He looks towards your hearts.', 'Sahih Muslim');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Repentance', 'Aquele que se arrepende de um pecado é como aquele que não tem pecado algum.', 'One who repents from sin is like one who has no sin.', 'Sunan Ibn Majah');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Patience', 'A magnitude da recompensa está proporcional à magnitude da provação. Quando Allah ama um povo, Ele coloca-o à prova.', 'The greatness of the reward is with the greatness of the trial. If Allah loves a people, He puts them to trial.', 'Sunan at-Tirmidhi');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Repentance', 'Meu Senhor! Perdoa-me e aceita o meu arrependimento, pois Tu és O Misericordioso, O Perdoador.', 'My Lord! Forgive me and accept my repentance, for You are the Acceptor of Repentance, the Forgiving.', 'Sunan Abi Dawud');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Overcoming', 'Olhai para aqueles que estão em situação inferior à vossa e não para os que estão acima de vós, para que não subestimeis as graças de Allah sobre vós.', 'Look at those who are lower than you but do not look at those who are higher than you, lest you should underestimate the favors of Allah upon you.', 'Sahih Muslim');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Patience', 'Quem se esforça para ser paciente, Allah concederá paciência. E ninguém recebeu uma dádiva melhor e mais ampla do que a paciência.', 'Whoever remains patient, Allah will make him patient. And nobody can be given a blessing better and greater than patience.', 'Sahih Bukhari');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Repentance', 'Se o Meu servo se aproxima de Mim um palmo, Eu aproximo-Me dele um braço. Se ele se aproxima um braço, Eu aproximo-Me dele a distância de dois braços estendidos. Se ele vem a Mim caminhando, Eu vou até ele correndo.', 'If the slave comes to Me by a span, I go to him by a cubit. If he comes to Me by a cubit, I go to him by a fathom. If he comes to Me walking, I go to him at speed.', 'Sahih Bukhari');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Overcoming', 'Um crente não é picado pelo mesmo buraco duas vezes (aprende com os seus erros).', 'A believer is not stung from the same hole twice.', 'Sahih Bukhari');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Patience', 'A paciência é uma luz resplandecente.', 'Patience is a brightness.', 'Sahih Muslim');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Repentance', 'Allah aceita o arrependimento do Seu servo enquanto este não estiver no momento final da morte.', 'Allah accepts the repentance of a slave as long as he is not at the point of death.', 'Sunan at-Tirmidhi');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Overcoming', 'Os melhores de vós são aqueles que possuem o melhor caráter e conduta.', 'The best among you are those who have the best manners and character.', 'Sahih Bukhari');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Forgiveness', 'Sê misericordioso com quem está na terra e Aquele que está nos céus terá misericórdia de ti.', 'Be merciful to those on earth and the One in the heavens will have mercy upon you.', 'Sunan at-Tirmidhi');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Patience', 'Certamente, com a dificuldade vem a facilidade.', 'Verily, with hardship comes ease.', 'Quran 94:6 (often quoted as Hadith point)');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Repentance', 'Um homem pecou e disse: ''Ó Allah, perdoa-me''. Allah disse: ''O Meu servo pecou e reconheceu que tem um Senhor que perdoa o pecado e dele pede contas''.', 'A man committed a sin and said: O Allah, forgive me. Allah said: My slave has committed a sin and realized that he has a Lord who forgives sin and takes to account for it.', 'Sahih Muslim');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Overcoming', 'Quem crê em Allah e no Último Dia, que diga o bem ou permaneça em silêncio.', 'He who believes in Allah and the Last Day should either speak good or remain silent.', 'Sahih Bukhari');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Patience', 'Este mundo é uma prisão para o crente e um paraíso para quem não crê.', 'The world is a prison for the believer and a paradise for the disbeliever.', 'Sahih Muslim');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Repentance', 'Allah estende a Sua mão durante a noite para que o pecador do dia se arrependa.', 'Allah stretches out His hand by night that the sinner of the day may repent.', 'Sahih Muslim');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Overcoming', 'Evita o que é proibido e serás o melhor dos adoradores.', 'Avoid that which is forbidden and you will be the best of worshippers.', 'Sunan at-Tirmidhi');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Patience', 'Espera pelo alívio, pois esperar pelo alívio é, por si só, um ato de adoração.', 'Wait for the relief, for waiting for relief is an act of worship.', 'Sunan at-Tirmidhi');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Forgiveness', 'Aquele que oculta as falhas de um muçulmano, Allah ocultará as suas falhas neste mundo e no outro.', 'Whoever conceals the faults of a Muslim, Allah will conceal his faults in this world and the Hereafter.', 'Sahih Muslim');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Overcoming', 'As ações mais amadas por Allah são aquelas que são mais constantes, mesmo que sejam pequenas.', 'The most beloved of deeds to Allah are those that are most consistent, even if they are small.', 'Sahih Bukhari');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Repentance', 'Lágrimas derramadas por temor a Allah não retornarão ao olho, assim como o leite não retorna ao úbere.', 'Tears shed out of fear of Allah will not return to the eye until the milk returns to the udder.', 'Sunan at-Tirmidhi');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Patience', 'Um muçulmano é irmão de outro muçulmano. Ele não o oprime nem o abandona diante do inimigo.', 'A Muslim is the brother of a Muslim. He does not wrong him nor does he hand him over to an enemy.', 'Sahih Bukhari');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Overcoming', 'Não consideres nenhuma boa ação como insignificante, mesmo que seja apenas receber o teu irmão com um rosto alegre.', 'Do not consider any good deed as insignificant, even if it is meeting your brother with a cheerful face.', 'Sahih Muslim');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Repentance', 'Certamente, as boas ações apagam as más ações.', 'Verily, good deeds do away with evil deeds.', 'Quran/Hadith consensus');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Patience', 'Se pedires algo, pede a Allah; se buscares ajuda, busca a ajuda de Allah.', 'If you ask, ask Allah; and if you seek help, seek help from Allah.', 'Sunan at-Tirmidhi');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Overcoming', 'Quem trilha um caminho em busca de conhecimento, Allah facilitará para ele um caminho para o Paraíso.', 'Whoever follows a path in pursuit of knowledge, Allah will make easy for him a path to Paradise.', 'Sahih Muslim');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Forgiveness', 'A caridade não diminui a riqueza.', 'Charity does not decrease wealth.', 'Sahih Muslim');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Patience', 'A religião é fácil, e ninguém se sobrecarrega na religião sem que seja vencido por ela.', 'Religion is easy, and no one overburdens himself in religion but he will be overwhelmed.', 'Sahih Bukhari');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Repentance', 'Alegra-te e espera por aquilo que te fará feliz.', 'Rejoice and hope for what will please you.', 'Sahih Bukhari');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Overcoming', 'A melhor luta (jihad) é lutar contra a sua própria alma e desejos por causa de Allah.', 'The best jihad is to struggle against your own soul and desires for the sake of Allah.', 'Daylami');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Patience', 'Diz a verdade, mesmo que seja amarga.', 'Speak what is true even if it is bitter.', 'Ibn Hibban');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Repentance', 'Allah aceita o arrependimento de quem se arrepende antes que o sol nasça no ocidente.', 'Allah accepts the repentance of whoever repents before the sun rises from the west.', 'Sahih Muslim');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Overcoming', 'Teme a Allah onde quer que estejas, e segue uma má ação com uma boa, pois ela a apagará.', 'Fear Allah wherever you are, and follow up a bad deed with a good one and it will wipe it out.', 'Sunan at-Tirmidhi');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Patience', 'O crente forte é melhor e mais amado por Allah do que o crente fraco.', 'The strong believer is better and more beloved to Allah than the weak believer.', 'Sahih Muslim');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Forgiveness', 'Aquele que não demonstra misericórdia não receberá misericórdia.', 'He who does not show mercy will not be shown mercy.', 'Sahih Bukhari');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Overcoming', 'A riqueza não consiste em ter muitos bens, mas sim em estar satisfeito consigo mesmo.', 'Wealth is not having many possessions, but wealth is being content with oneself.', 'Sahih Bukhari');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Patience', 'Sê neste mundo como se fosses um estranho ou um viajante.', 'Be in this world as if you were a stranger or a traveler.', 'Sahih Bukhari');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Repentance', 'As portas do arrependimento estão abertas até que o sol nasça no ocidente.', 'The gates of repentance are open until the sun rises from the west.', 'Sahih Muslim');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Overcoming', 'O homem segue a religião do seu amigo, portanto, que cada um de vós veja bem quem escolhe para amigo.', 'A man is upon the religion of his friend, so let each of you look at whom he befriends.', 'Sunan Abi Dawud');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Patience', 'Adora a Allah como se O visses; pois, se tu não O vês, Ele certamente te vê.', 'Worship Allah as if you see Him, for if you do not see Him, He sees you.', 'Sahih Bukhari');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Forgiveness', 'Perdoa, e serás perdoado.', 'Forgive, and you will be forgiven.', 'Musnad Ahmad');
INSERT INTO public.hadiths (topic, content_pt, content_en, source) VALUES ('Overcoming', 'A caneta foi erguida e as páginas secaram (o que está destinado acontecerá).', 'The pen has been lifted and the pages have dried.', 'Sunan at-Tirmidhi');
